version: '3'
services:
  redis:
    image: redis:7.0-alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: websocket-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - REDIS_HOST=redis-server
      - DB_HOST=${{ secrets.DB_ENDPOINT }}
      - DB_PORT=3306
      - DB_NAME=admin
      - DB_USER=<DATABASE_USERNAME>
      - DB_PASSWORD=${{ secrets.DB_PASSWORD }}
    depends_on:
      - redis

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
