version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chairing-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://${{ secrets.DB_ENDPOINT }}:3306/chairingproject
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=${{ secrets.DB_PASSWORD }}
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      - mysql
      - redis

  redis:
    image: redis:7.0-alpine
    container_name: redis-server
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: chairingproject
      MYSQL_USER: admin
      MYSQL_PASSWORD: your-password
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: