name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify source files
        run: |
          if [ ! -f ./docker-compose.yml ]; then
            echo "Error: docker-compose.yml not found"
            exit 1
          fi
          if [ ! -f ./build/libs/*.jar ]; then
            echo "Error: JAR file not found"
            exit 1
          fi

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "./docker-compose.yml"
          target: "~"
          debug: true
          strip_components: 2

      - name: Check transferred files on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            ls -al /home/ec2-user/
