name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Generate .env File
        run: |
          echo "SPRING_DATASOURCE_URL=jdbc:mysql://${{ secrets.DB_ENDPOINT }}:3306/chairingproject" >> .env
          echo "SPRING_DATASOURCE_USERNAME=admin" >> .env
          echo "SPRING_DATASOURCE_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "SPRING_DATA_REDIS_HOST=redis" >> .env
          echo "SPRING_DATA_REDIS_PORT=6379" >> .env

      - name: Copy Docker Compose files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: |
            ./docker-compose.yml
            ./.env
          target: "~"

      - name: SSH Commands to Deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script_stop: true
          script: |
            sudo yum update -y && sudo yum install -y docker docker-compose
            sudo systemctl start docker
            cd ~
            docker-compose down
            docker-compose up -d
